### ISSUE TITLE
🌎 Create a RESTful API 

### ISSUE THREAD

**Issue by nesimtunc** [evrimagaci/periodum-api#3]
Since now we have imported existing db #10 feature done, we can start to implement fully support of existing API only related parts -> https://github.com/evrimagaci/periodum/blob/main/server/routes.js#L7-L97

End points should NOT contains "api" since this app is going to work on "api.periodum.com"

Future implementations or good to have at the beginning if possible:

- Rate Limiter (we can use a library)

PS: This can be implemented after #2 task

**Comment by asiminnesli** [comment]
bu endpoint periodum database in kullanıcak ise yapımına başlayabilirim. Bir ara database değiştirme konusu gündemdeydi ondan soruyorum.

**Comment by nesimtunc** [comment]
Now, this task can be done.
