### ISSUE TITLE
Integrate GitHub Actions for CI

### ISSUE THREAD

**Issue by nesimtunc** [evrimagaci/periodum-api#7]
For now, only GitHub actions would be enough for us to validate coding style, later after unit tests we can add that step too.

It should run `lint`

**Comment by RishiKumarRay** [comment]
do we have to add only lint  step?

**Comment by nesimtunc** [comment]
Yes, we want to run on PRs when people want to merge, so, we can validate syntax, we currently have this on our main project, instead of yarn it will be npm

https://github.com/evrimagaci/periodum/blob/main/.github/workflows/test.yml

**Comment by nesimtunc** [comment]
Sorry @RishiKumarRay this has been done #9 Thank you for your interest,  and you're welcome to contribute other tasks.
